#version 460 core
layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D texture;

#define MAX_SHAPE 16 // Maximum number of shapes to render

uniform int shapes[MAX_SHAPE]; // The value design the shapes to be rendered
// -1 : none
//  0 : circle
//  1 : triangle
//  2 : hexagon

uniform float radius[MAX_SHAPE];
uniform float border[MAX_SHAPE];
uniform float angle[MAX_SHAPE];
uniform float time;
